### ISSUE TITLE
TODO's as i think of them

### ISSUE THREAD

**Issue by pvyParts** [pvyParts/allianceauth-corp-tools#1]
### Detail Views copy pasta
- [x] Master Admin Menu
- [x] Char Deets ( Per Char, Grouped to Account )
- [x] Char Asset ( account )
- [x] Char Wallet ( account )
- [x] Char Skills ( Per Char, Grouped to Account )
- [x] Char Doctrines ( Per Char, in skill screen ( maybe add a limit ) ) 
- [x] Char Clones
- [x] Char Skill Queues ( Per Char, Grouped to Account )

### Update tasks
- [x] Char Pub Data
- [x] Char skills
- [x] Char Skill Queue
- [x] Char Wallet
- [x] Char Clones
- [x] Char Assets
- [ ] Corp Mining Ledger
- [x] Corp Mining Pulls
- [x] Corp Structures
- [x] Corp Wallet
- [x] Corp Assets
- [x] Bulk Location updates 

### Notification tasks
- [x] Fuel to Webhook
- [x] Rest to Webhook
